version: '2'
services:
  mariadb:
    image: mariadb:10
    hostname: mariadb
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=@ccs2011
      - "MYSQL_ROOT_HOST=%"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    hostname: phpmyadmin
    ports:
      - 9999:80
    environment:
      - PMA_HOST=mariadb